[package]
name = "task_manager"
version = "0.1.0"
edition = "2024"
authors = ["talonlikeaclaw"]

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
